# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
assistant_id: 20241217-152652-steel-specialist

# Configuration for Rasa NLU.
language: en

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 3
  max_ngram: 5
- name: LanguageModelFeaturizer
  model_weights: "sentence-transformers/paraphrase-MiniLM-L6-v2"
- name: DIETClassifier
  epochs: 100
  constrain_similarities: True
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1

# Configuration for Rasa Core.
policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
- name: RulePolicy
  core_fallback_action_name: "utter_action_default_fallback"
  core_fallback_threshold: 0.3
  enable_fallback_prediction: True
